# Site settings
title: Game-Play
description: Pengalaman gaming HTML5 terbaik dengan koleksi game arcade, action, puzzle, dan olahraga yang terbaru dan gratis. Mainkan game langsung di browser tanpa perlu download!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:title/

# Plugins - semua fitur feed dan sitemap menggunakan plugin kustom
plugins: []

# Feed dan sitemap dibuat melalui plugin kustom di _plugins/

# Collections
collections:
  gameposts:
    output: true
    permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "gameposts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# API settings
game_monetize_api: "https://rss.gamemonetize.com/rssfeed.php?format=json&category=All&type=html5&popularity=newest&company=All&amount=All"

# SEO settings
social:
  name: Game Monetize Portal
  links:
    - https://twitter.com/yourusername
    - https://facebook.com/yourusername
    - https://instagram.com/yourusername

# HTML Compression settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

# Other settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - crontab_setup.sh
  - deploy.sh
  - .github
